version: "3.7"
services:
  rucio:
    image: rucio-dev
    container_name: rucio-dev
    ports:
      - "443:443"
    links:
      - postgres:postgres
      - graphite:graphite
    volumes:
      - ./rucio/tools:/opt/rucio/tools
      - ./rucio/bin:/opt/rucio/bin
      - ./rucio/lib:/opt/rucio/lib
    depends_on:
      - postgres

  rucio-client:
    image: rucio-client
    links:
      - postgres:postgres
    volumes:
      - ./rucio/tools:/opt/rucio/tools
      - ./rucio/bin:/opt/rucio/bin
      - ./rucio/lib:/opt/rucio/lib
    depends_on:
      - rucio
    environment:
      - RUCIO_ACCOUNT=root

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"

  storage_xrootd_0:
    image: jimbat/fnal-xrootd
    expose: 
      - "1094"
    environment:
      - XROOTD_SITE_NAME=bjwhite_test_xrootd_standalone_0

  storage_xrootd_1:
    image: jimbat/fnal-xrootd
    expose:
      - "1094"
    environment:
      - XROOTD_SITE_NAME=bjwhite_test_xrootd_standalone_1
