version: "3.7"
services:
  rucio:
    image: rucio-dev
    container_name: rucio-dev
    ports:
      - "443:443"
      # Remote Pdb port 
      - "4444:4444"
    links:
      - postgres:postgres
      - graphite:graphite
    volumes:
      - ./rucio/tools:/opt/rucio/tools
      - ./rucio/bin:/opt/rucio/bin
      - ./rucio/lib:/opt/rucio/lib
      - /etc/grid-security/certificates:/etc/grid-security/certificates
    depends_on:
      - postgres
      - memcached
    # Required for Remote Pdb
    stdin_open: true
    tty: true

  rucio-client:
    image: rucio-client
    links:
      - postgres:postgres
    volumes:
      - ./rucio/tools:/opt/rucio/tools
      - ./rucio/bin:/opt/rucio/bin
      - ./rucio/lib:/opt/rucio/lib
      - /etc/grid-security/certificates:/etc/grid-security/certificates
      - /tmp/x509up_u51660:/tmp/x509up_u51660
    environment:
      - RUCIO_ACCOUNT=root
      - X509_USER_PROXY=/tmp/x509up_u51660
    depends_on:
      - rucio

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"

  storage_xrootd_0:
    image: jimbat/fnal-xrootd
    expose: 
      - "1094"
    environment:
      - XROOTD_SITE_NAME=bjwhite_test_xrootd_standalone_0

  storage_xrootd_1:
    image: jimbat/fnal-xrootd
    expose:
      - "1094"
    environment:
      - XROOTD_SITE_NAME=bjwhite_test_xrootd_standalone_1

  memcached:
    image: memcached:latest
    environment: 
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
