
FROM rucio/rucio-dev

RUN yum install -y postgresql-devel

RUN pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install boto3 psycopg2-binary

# BJWHITE additions
COPY rucio.cfg_bjwhite $RUCIOHOME/etc/rucio.cfg
COPY alembic.ini_bjwhite $RUCIOHOME/etc/alembic.ini

CMD ["httpd", "-D", "FOREGROUND"]
