
FROM rucio/rucio-dev

RUN yum install -y postgresql-devel

RUN pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install boto3 psycopg2-binary

# BJWHITE additions

COPY alembic.ini_bjwhite $RUCIOHOME/etc/alembic.ini
COPY rucio_create_bjwhite.sh $RUCIOHOME/rucio_create_bjwhite.sh
COPY rucio_init_db.sh $RUCIOHOME/rucio_init_db.sh
COPY rucio_create_rses.sh $RUCIOHOME/rucio_create_rses.sh
COPY wait-for-it.sh $RUCIOHOME/wait-for-it.sh
RUN chmod +x $RUCIOHOME/rucio_init_db.sh && \
    chmod +x $RUCIOHOME/rucio_create_rses.sh && \
    chmod +x $RUCIOHOME/wait-for-it.sh && \
    chmod +x $RUCIOHOME/rucio_create_bjwhite.sh

# Rucio Config with X509 Auth
COPY rucio.cfg_bjwhite_x509 $RUCIOHOME/etc/rucio.cfg

# Volume mounting at runtime would stomp this file, so add it to RUCIOHOME in order
#   to copy it into the code directory when rucio_init_db.sh is run
COPY util.py_bjwhite $RUCIOHOME/util.py

CMD ["tail", "-f", "/dev/null"]
